name: CD - Despliegue

on:
  push:
    branches:
      - desarrollo

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Parar contenedores antiguos
        run: |
          docker-compose down || true
          docker rm -f mini-secure-app || true

      - name: Limpiar imágenes antiguas (opcional)
        run: docker system prune -f || true

      - name: Construir y levantar aplicación
        run: docker-compose up -d --build

      - name: Ver contenedores
        run: docker ps

      - name: Esperar arranque
        run: sleep 10

      - name: Test app
        run: curl http://localhost:3001 || true
